#Disable decapitation for passive mobs
disablePassive = false
#
# Mobs to disable decapitation for
# Separate multiple entries with a comma.
#
#Example: "minecraft:pig,some_mod:some_mob"
blackListedMobs = ""
#Chance of mobs being decapitated
#Range: 0.0 ~ 1.0
chance = 0.2

