
["Arrow turret"]
	#Range: 10.0 ~ 500.0
	Health = 60.0
	#Range: 8.0 ~ 100.0
	Range = 32.0
	#Range: 0.0 ~ 100.0
	Armor = 3.0
	#In ticks
	#Range: 10 ~ 60
	"Fire rate" = 20
	#Range: 1 ~ 100
	"Base damage" = 6

["Bullet turret"]
	#Range: 10.0 ~ 500.0
	Health = 60.0
	#Range: 8.0 ~ 100.0
	Range = 32.0
	#Range: 0.0 ~ 100.0
	Armor = 3.0
	#In ticks
	#Range: 10 ~ 60
	"Fire rate" = 20
	#Range: 1 ~ 100
	"Iron bullet damage" = 8
	#Range: 1 ~ 100
	"Gold bullet damage" = 7

["Fire charge turret"]
	#Range: 10.0 ~ 500.0
	Health = 60.0
	#Range: 8.0 ~ 100.0
	Range = 32.0
	#Range: 0.0 ~ 100.0
	Armor = 3.0
	#In ticks
	#Range: 10 ~ 60
	"Fire rate" = 20
	#Range: 1 ~ 100
	Damage = 6

["Brick turret"]
	#Range: 10.0 ~ 500.0
	Health = 60.0
	#Range: 8.0 ~ 100.0
	Range = 32.0
	#Range: 0.0 ~ 100.0
	Armor = 3.0
	#In ticks
	#Range: 10 ~ 60
	"Fire rate" = 20
	#Range: 1 ~ 100
	"Brick damage" = 9
	#Range: 1 ~ 100
	"Nether brick damage" = 10

["Gauss turret"]
	#Range: 10.0 ~ 500.0
	Health = 60.0
	#Range: 8.0 ~ 100.0
	Range = 32.0
	#Range: 0.0 ~ 100.0
	Armor = 3.0
	#In ticks
	#Range: 10 ~ 60
	"Fire rate" = 20
	#Range: 1 ~ 100
	Damage = 12

["Cobble turret"]
	#Range: 10.0 ~ 500.0
	Health = 60.0
	#Range: 0.0 ~ 100.0
	Range = 32.0
	#Range: 0.0 ~ 100.0
	Armor = 3.0
	#In ticks
	#Range: 10 ~ 60
	"Fire rate" = 20
	#Range: 1 ~ 100
	Damage = 3

